{
 "title": "PostgreSQL",
 "tags": [
  "postgresql",
  "postgres_exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pg_stat_activity_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"malikov\"}[5m]) + rate(pg_stat_database_xact_rollback{datname=\"malikov\"}[5m])",
     "legendFormat": "transactions/s"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=\"malikov\"} / (pg_stat_database_blks_hit{datname=\"malikov\"} + pg_stat_database_blks_read{datname=\"malikov\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Fetched/Returned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"malikov\"}[5m])",
     "legendFormat": "tup_fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"malikov\"}[5m])",
     "legendFormat": "tup_returned"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"malikov\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{datname=\"malikov\"}[5m])",
     "legendFormat": "deadlocks/s"
    }
   ]
  },
  {
   "title": "Temp Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{datname=\"malikov\"}[5m])",
     "legendFormat": "temp_bytes/s"
    }
   ]
  }
 ]
}